project_id = "utapcrvduextlzahfesv"

[functions.submit-feedback]
verify_jwt = false

[functions.submit-feedback-ai]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.semantic-code-search]
verify_jwt = false

[functions.admin-chat]
verify_jwt = false